export const PAL = {
    'T': 'rgba(0,0,0,0)', 'B': '#000000', 'W': '#FFFFFF', 'R': '#FF0000', 'O': '#FFA500', 
    'H': '#654321', 'Y': '#FFFF00', 'U': '#0000FF', 'S': '#FFC0CB', 'G': '#777777', 
    'D': '#444444', 'L': '#8B4513', 'A': '#2b2b2b', 'K': '#555555', 'V': '#00FF00', 'M': '#FFD700', 'P': '#FF69B4',
    'C': '#2E7D32', 'E': '#5D4037', 'F': '#795548', 'X': '#EEEEEE', 'Q': '#FF8C00'
};

export const SPRITES_DATA = {
    chicken_idle: [
        "TTTTTTTTTTTTTTTT", "TTTTTTTTTTTRRRTT", "TTTTTTTTTTTRRRTT", "TTTTTTTTTBWWWWWT",
        "TTTTTTTTBWWWWWWW", "TTTTTTTBWWBWWWWW", "TTTTTTTWWWWWWWWO", "TTTBBBBWWWWWWWOO",
        "TTBWWWWWWWWWWTTT", "TBBWWWWWWWWWWTTT", "TTBWWWWWWWWWTTTT", "TTTBBBBBBBBBTTTT",
        "TTTTTTHHTHHTTTTT", "TTTTTTHHTHHTTTTT", "TTTTTTHHTHHTTTTT", "TTTTTTBBTTBBTTTT"
    ],
    chicken_walk1: [
        "TTTTTTTTTTTTTTTT", "TTTTTTTTTTTRRRTT", "TTTTTTTTTTTRRRTT", "TTTTTTTTTBWWWWWT",
        "TTTTTTTTBWWWWWWW", "TTTTTTTBWWBWWWWW", "TTTTTTTWWWWWWWWO", "TTTBBBBWWWWWWWOO",
        "TTBWWWWWWWWWWTTT", "TBBWWWWWWWWWWTTT", "TTBWWWWWWWWWTTTT", "TTTBBBBBBBBBTTTT",
        "TTTTTTHHTHHTTTTT", "TTTTTTHHTTTTTTTT", "TTTTTTTHHTTTTTTT", "TTTTTTTBBTTBBTTT"
    ],
    chicken_walk2: [
        "TTTTTTTTTTTTTTTT", "TTTTTTTTTTTRRRTT", "TTTTTTTTTTTRRRTT", "TTTTTTTTTBWWWWWT",
        "TTTTTTTTBWWWWWWW", "TTTTTTTBWWBWWWWW", "TTTTTTTWWWWWWWWO", "TTTBBBBWWWWWWWOO",
        "TTBWWWWWWWWWWTTT", "TBBWWWWWWWWWWTTT", "TTBWWWWWWWWWTTTT", "TTTBBBBBBBBBTTTT",
        "TTTTTTHHTHHTTTTT", "TTTTTTTTTHHTTTTT", "TTTTTTTTTTHHTTTT", "TTTTTTTBBTTBBTTT"
    ],
    chicken_kick: [
        "TTTTTTTTTTTTTTTT", "TTTTTTTTTRRRTTTT", "TTTTTTTTBWWWBBTT", "TTTTTTTBWWBWWWBT",
        "TTTBBBBWWWWWWWWO", "TTBWWWWWWWWWWWOO", "TBBWWWWWWWWWWTTT", "TTBWWWWWWWWWTTTT",
        "TTTBBBBBBBBTTTTT", "TTTTTHHTTTTTTTTT", "TTTTTHHTTTTTTTTT", "TTTTTHHHHHHHTTTT",
        "TTTTTTTTTTHHHTTT", "TTTTTTTTTTTHHTTT", "TTTTTTTTTTTBBTTT", "TTTTTTTTTTTTTTTT"
    ],
    chicken_girl: [
        "TTTTTTTTTTTTTTTT", "TTTTTTTTTTTPPPTT", "TTTTTTTTTTTPPPTT", "TTTTTTTTTBWWWWWT",
        "TTTTTTTTBWWWWWWW", "TTTTTTTBWWBWWWWW", "TTTTTTTWWWWWWWWO", "TTTBBBBWWWWWWWOO",
        "TTBWWWWWWWWWWTTT", "TBBWWWWWWWWWWTTT", "TTBWWWWWWWWWTTTT", "TTTBBBBBBBBBTTTT",
        "TTTTTTHHTHHTTTTT", "TTTTTTHHTHHTTTTT", "TTTTTTHHTHHTTTTT", "TTTTTTBBTTBBTTTT"
    ],
    chicken_baby: [
        "TTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTT",
        "TTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTT", "TTTTTYYYYYTTTTTT",
        "TTTTYYYYYYYOTTTT", "TTTTBYYYYYYOTTTT", "TTTTYYYYYYYTTTTT", "TTTTTYYYYYTTTTTT",
        "TTTTTTTHTHTTTTTT", "TTTTTTTHTHTTTTTT", "TTTTTTTHTHTTTTTT", "TTTTTTTBTBTTTTTT"
    ],
    human_stand: [
        "TTTTTTSSTTTTTTTT", "TTTTTSSSSTTTTTTT", "TTTTTSSSSTTTTTTT", "TTTTTTBBTTTTTTTT",
        "TTTTTRRRRTTTTTTT", "TTTSSRRRRSTTTTTT", "TTTTRRRRRRTTTTTT", "TTTTUUUUUUTTTTTT",
        "TTTTTUUUUTTTTTTT", "TTTTTUUUUTTTTTTT", "TTTTTUUUUTTTTTTT", "TTTTTBBTBBTTTTTT"
    ],
    human_sit: [
        "TTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTT", "TTTTTTSSTTTTTTTT", "TTTTTSSSSTTTTTTT",
        "TTTTTSSSSTTTTTTT", "TTTTTTBBTTTTTTTT", "TTTTTRRRRTTTTTTT", "TTTSSRRRRSTTTTTT",
        "TTTTRRRRRRTTTTTT", "TTTTUUUUUUTTTTTT", "TTTTUUUUUUUUUTTT", "TTTTBBTTTBBTTTTT"
    ],
    human_dance1: [
        "TTTTTTSSTTTTTTTT", "TTTTTSSSSTTTTTTT", "TTTTTSSSSTTTTTTT", "TTTTTTBBTTTTTTTT",
        "TTTSSRRRRSTTTTTT", "TTTTTRRRRTTTTTTT", "TTTTRRRRRRTTTTTT", "TTTTUUUUUUTTTTTT",
        "TTTTTUUUUTTTTTTT", "TTTTTUUUUTTTTTTT", "TTTTTUUUUTTTTTTT", "TTTTTBBTBBTTTTTT"
    ],
    human_dance2: [
        "TTSSSSSSTTTTTTTT", "TTTTTSSSSTTTTTTT", "TTTTTSSSSTTTTTTT", "TTTTTTBBTTTTTTTT",
        "TTTTTRRRRTTTTTTT", "TTTSSRRRRSTTTTTT", "TTTTRRRRRRTTTTTT", "TTTTUUUUUUTTTTTT",
        "TTTTTUUUUTTTTTTT", "TTTTTUUUUTTTTTTT", "TTTTTUUUUTTTTTTT", "TTTTTBBTBBTTTTTT"
    ],
    human_green: [
        "TTTTTTSSTTTTTTTT", "TTTTTSSSSTTTTTTT", "TTTTTSSSSTTTTTTT", "TTTTTTBBTTTTTTTT",
        "TTTTTVVVVTTTTTTT", "TTTSSVVVVSTTTTTT", "TTTTVVVVVVTTTTTT", "TTTTUUUUUUTTTTTT",
        "TTTTTUUUUTTTTTTT", "TTTTTUUUUTTTTTTT", "TTTTTUUUUTTTTTTT", "TTTTTBBTBBTTTTTT"
    ],
    smoker_1: [
        "TTTTTTSSTTTTTTTT", "TTTTTSSSSTTTTTTT", "TTTTTSSSSTTWWTTT", "TTTTTTBBTTTTTTTT",
        "TTTTTRRRRTTTTTTT", "TTTSSRRRRTTTTTTT", "TTTTRRRRRRTTTTTT", "TTTTUUUUUUTTTTTT",
        "TTTTTUUUUTTTTTTT", "TTTTTUUUUTTTTTTT", "TTTTTUUUUTTTTTTT", "TTTTTBBTBBTTTTTT"
    ],
    smoker_2: [
        "TTTTTTSSTTTTTTTT", "TTTTTSSSSTTTTTTT", "TTTTTSSSSTTWQTTT", "TTTTTTBBTTTTTTTT",
        "TTTTTRRRRTTTTTTT", "TTTTTRRRRSTTTTTT", "TTTTRRRRRRTTTTTT", "TTTTUUUUUUTTTTTT",
        "TTTTTUUUUTTTTTTT", "TTTTTUUUUTTTTTTT", "TTTTTUUUUTTTTTTT", "TTTTTBBTBBTTTTTT"
    ],
    butcher: [
        "TTTTTTSSTTTTTTTT", "TTTTTSSSSTTTTTTT", "TTTTTSSSSTTTTTTT", "TTTTTTBBTTTTTTTT",
        "TTGGTWWWWRRTTTTT", "TTGGTWWWWSTTTTTT", "TTGGTWWWWRRTTTTT", "TTTDTBBBBBBTTTTT",
        "TTTTTBBBBTTTTTTT", "TTTTTBBBBTTTTTTT", "TTTTTBBBBTTTTTTT", "TTTTTBBTBBTTTTTT"
    ],
    oikotie: [
        "TTTTTTSSTTTTTTTT", "TTTTTSSSSTTTTTTT", "TTTTTSSSSTTTTTTT", "TTTTTTBBTTTTTTTT",
        "TTTTTUUUUTTTTTTT", "TTTSSUYUUSTTTTTT", "TTTTUUYUUUTTTTTT", "TTTTUUUUUUTTTTTT",
        "TTTTTUUUUTTTTTTT", "TTTTTUUUUTTTTTTT", "TTTTTUUUUTTTTTTT", "TTTTTBBTBBTTTTTT"
    ],
    bat_guy_1: [
        "TTTTTTSSTTTTTTTT", "TTTTTSSSSTTTTTTT", "TTTTTSSSSTLLLLTT", "TTTTTTBBTTLLLLTT",
        "TTTTTDDDDTTLLTTT", "TTTSSDDDDSTLLTTT", "TTTTDDDDDDTTLLTT", "TTTTBBBBBBTTTTTT",
        "TTTTTBBBBTTTTTTT", "TTTTTBBBBTTTTTTT", "TTTTTBBBBTTTTTTT", "TTTTTBBTBBTTTTTT"
    ],
    bat_guy_2: [
        "TTTTTTSSTTTTTTTT", "TTTTTSSSSTTTTTTT", "TTTTTSSSSTTTTTTT", "TTTTTTBBTTTTTTTT",
        "TTTTTDDDDTTTTTTT", "TTTSSDDDDSTTTTTT", "TLLTDDDDDDTTTTTT", "TLLTBBBBBBTTTTTT",
        "TLLTTBBBBTTTTTTT", "TLLTTBBBBTTTTTTT", "TLLTTBBBBTTTTTTT", "TTTTTBBTBBTTTTTT"
    ],
    burger: [
        "TTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTT", "TTTTTTMMMMTTTTTT", "TTTTTMMMMMMTTTTT",
        "TTTTTLLLLLLTTTTT", "TTTTTVVVVVVTTTTT", "TTTTTRRRRRRTTTTT", "TTTTTMMMMMMTTTTT",
        "TTTTTTMMMMTTTTTT", "TTTTTTTTTTTTTTTT"
    ],
    leg: [
        "TTTTTTTT", "TTTTTTTT", "TTWWTTTT", "TWWWWTHT", "TTWWWTHH",
        "TWWWWTHT", "TTWWTTTT", "TTTTTTTT"
    ],
    bottle: [
        "TTTTTTTT", "TTTVVTTT", "TTTVVTTT", "TTVVVVTT",
        "TTVVVVTT", "TTVVVVTT", "TTVVVVTT", "TTTTTTTT"
    ],
    sign: [
        "TTTTTTTT", "TLLLLLLT", "TLLLLLLT", "TLLLLLLT",
        "TLLLLLLT", "TTTLLTTT", "TTTLLTTT", "TTTLLTTT"
    ],
    table: [
        "TTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTT",
        "TTTTTTTTTTTTTTTT", "LLLLLLLLLLLLLLLL", "LLLLLLLLLLLLLLLL", "TDDTTTTTTTTTTDDT",
        "TDDTTTTTTTTTTDDT", "TDDTTTTTTTTTTDDT", "TDDTTTTTTTTTTDDT", "TDDTTTTTTTTTTDDT"
    ],
    bench: [
        "TTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTT",
        "FFFFFFFFFFFFFFFF", "TTTTTTTTTTTTTTTT", "FFFFFFFFFFFFFFFF", "FFFTTTTTTTTTTFFF",
        "FFFTTTTTTTTTTFFF", "FFFTTTTTTTTTTFFF", "FFFTTTTTTTTTTFFF", "FFFTTTTTTTTTTFFF"
    ],
    basket: [
        "TTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTT",
        "TTTTTYYYYTTTTTTT", "TTTTYYYYYYTTTTTT", "TTTRWRWRWRWTTTTT", "TTTRWRWRWRWTTTTT",
        "TTTRWRWRWRWTTTTT", "TTTWRWRWRWRTTTTT", "TTTWRWRWRWRTTTTT", "TTTWRWRWRWRTTTTT"
    ],
    brick_wall: [
        "TTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTT", "TTTTTTTTTTTTTTTT",
        "LLLLLLLLLLLLLLLL", "BDDBBDDBBDDBBDDB", "LLLLLLLLLLLLLLLL", "DBBDDBBDDBBDDBBD",
        "LLLLLLLLLLLLLLLL", "BDDBBDDBBDDBBDDB", "LLLLLLLLLLLLLLLL", "DBBDDBBDDBBDDBBD"
    ],
    trash: [
        "TTTTTTTTTTTTTTTT", "TTTTTDTTDTTTTTTT", "TTTTDDDDDDTTTTTT", "TTTGGGGGGGGTTTTT",
        "TTTGGGGGGGGTTTTT", "TTTGGGGGGGGTTTTT", "TTTGGGGGGGGTTTTT", "TTTGGGGGGGGTTTTT",
        "TTTGGGGGGGGTTTTT", "TTTGGGGGGGGTTTTT", "TTTGGGGGGGGTTTTT", "TTTDDDDDDDDTTTTT"
    ],
    car_blue: [
        "TTTTTTTTTTTTTTTT", "TTTTTTUUUUUTTTTT", "TTTTTUUWWWUUTTTT", "TTTUUUUUUUUUUUTT",
        "TTYUUUUUUUUUUUTT", "TDDDUUUUUUUUUDDD", "DBBBDTTTTTTTDBBB", "TDDDTTTTTTTTTDDD"
    ],
    car_red: [
        "TTTTTTTTTTTTTTTT", "TTTTTTRRRRRTTTTT", "TTTTTRRWWWRRTTTT", "TTTRRRRRRRRRRRTT",
        "TTYRRRRRRRRRRRTT", "TDDDRRRRRRRRRDDD", "DBBBDTTTTTTTDBBB", "TDDDTTTTTTTTTDDD"
    ],
    tree: [
        "TTTTTTTCCCTTTTTT", "TTTTTCCCCCCCTTTT", "TTTTCCCCCCCCCCTT", "TTCCCCCCCCCCCCTT",
        "TCCCCCCCCCCCCCCX", "CCCCCCCCCCCCCCCC", "TCCCCCCCCCCCCCCX", "TTCCCCCCCCCCCCTT",
        "TTTTCCCCCCCCCCTT", "TTTTTTTEEEETTTTT", "TTTTTTTEEEETTTTT", "TTTTTTTEEEETTTTT",
        "TTTTTTTEEEETTTTT", "TTTTTTTEEEETTTTT", "TTTTTTTEEEETTTTT", "TTTTTTTEEEETTTTT"
    ],
    arrow: [
        "TTTTTTTT", "TTTTTTTT", "TTTMMTTT", "TTTMMTTT", "TTMMMMTT",
        "TMMMMMMT", "MMMMMMMM", "TTMMMMTT"
    ]
};
